# Generated by Django 4.2.2 on 2023-06-17 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_base'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Base',
        ),
    ]
